name: Deploy Static Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.HOME_SERVER }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no user@your-server-ip "
        sudo rm -rf /var/www/static-website/*
        "
        scp -r ./ rootu@192.168.18.183:/var/www/static-website/
